# Generated by Django 3.2.13 on 2022-07-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220703_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='id',
        ),
    ]
