# Generated by Django 3.2.13 on 2022-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('PAID', 'paid')], max_length=10),
        ),
    ]
