# Generated by Django 3.2.13 on 2022-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, max_length=15)),
                ('paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, max_length=15)),
                ('returns', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('PAID', 'paid')], default='NEW', max_length=10),
        ),
    ]
