# Generated by Django 3.2.13 on 2022-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220703_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.JSONField(default={'discount': '0.00', 'paid': '0.00', 'returns': '0.00', 'total': '0.00'}),
        ),
    ]
